language: php

sudo: false

php:
  - 7.4
  - 8.0
  - 8.1
  - 8.2
  - 8.3

jobs:
  include:
    - dist: precise
      php: 8.3
    - dist: trusty
      php: 8.2
    - dist: trusty
      php: 8.1

matrix:
    fast_finish: true

branches:
  only:
    - master
    - 2.x

install:
  - composer install

script:
  - vendor/bin/phpunit
